apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: classscheduling

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: classscheduling-backend:2.0

          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: backend-secret

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"