apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: classscheduling

type: Opaque

stringData:
  DB_PASSWORD: postgres123

  JWT_SECRET: seu secret aqui

  BREVO_API_KEY: sua chave aqui

  BREVO_FROM_EMAIL: seu email aqui

  BREVO_FROM_NAME: seu nome da chave aqui