spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}

brevo:
  api-key: ${BREVO_API_KEY}
  from-email: ${BREVO_FROM_EMAIL}
  from-name: ${BREVO_FROM_NAME}

server:
  port: ${PORT:8080}