spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

  logging:
  level:
    org.springframework.security: DEBUG

  metrics:
    tags:
      application: classscheduling
